apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: watchly-3d-models
  labels:
    app: postgresql
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:  
    path: /data/postgresql
