apiVersion: v1
kind: Service
metadata:
  name: watchly
  namespace: watchly
  labels:
    app: watchly
spec:
  selector:
    app: watchly
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP
