apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: udp-joker-secrets
  namespace: udp-joker
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: udp-joker-secrets
    creationPolicy: Owner
  data:
    - secretKey: BOT_TOKEN
      remoteRef:
        key: udp-joker
        property: botToken
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
