apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: siyuan-workspace
  namespace: siyuan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard  # uncomment & set per your cluster
