apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: siyuan-secrets
  namespace: siyuan
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: siyuan-secrets
    creationPolicy: Owner
  data:
    - secretKey: accessAuthCode
      remoteRef:
        key: siyuan
        property: accessAuthCode
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
