apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: incept1on/inceptech-nginx-balancer:master
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: rtmps
              containerPort: 1936
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: tls
              mountPath: /etc/nginx/pki
              readOnly: true
      terminationGracePeriodSeconds: 30
      
      volumes:
        - name: tls
          secret:
            secretName: displayify-secrets
            items:
              - key: server.crt
                path: server.crt
              - key: server.key
                path: server.key
              - key: ca.crt
                path: ca.crt
