apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: incept1on/inceptech-nginx-balancer:master
          imagePullPolicy: Always
          ports:
            # HTTP/HTTPS ports
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /nginx-health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: tls
              mountPath: /etc/nginx/pki
              readOnly: true
            - name: siyuan-tls
              mountPath: /etc/nginx/certs/siyuan
              readOnly: true
            - name: argocd-server-tls
              mountPath: /etc/nginx/certs/argocd
              readOnly: true
            - name: watchly-server-tls
              mountPath: /etc/nginx/certs/watchly
              readOnly: true
      terminationGracePeriodSeconds: 30
      
      volumes:
        - name: tls
          secret:
            secretName: displayify-secrets
            items:
              - key: server.crt
                path: server.crt
              - key: server.key
                path: server.key
              - key: ca.crt
                path: ca.crt
        - name: siyuan-tls
          secret:
            secretName: siyuan-tls
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
        - name: argocd-server-tls
          secret:
            secretName: argocd-server-tls
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
        - name: watchly-server-tls
          secret:
            secretName: watchly-server-tls
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
