apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: displayify-lb-secrets
  namespace: nginx-load-balancer
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: displayify-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: displayify
        conversionStrategy: Default	
        decodingStrategy: None
        nullBytePolicy: Ignore
        metadataPolicy: None
