apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: ts3-voice
      port: 9987
      targetPort: 9987
      protocol: UDP
    - name: ts3-query
      port: 10011
      targetPort: 10011
      protocol: TCP
    - name: ts3-file
      port: 30033
      targetPort: 30033
      protocol: TCP
