apiVersion: apps/v1
kind: Deployment
metadata:
  name: restoration-watchly
  namespace: restoration-watchly
  labels:
    app: restoration-watchly
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restoration-watchly
  template:
    metadata:
      labels:
        app: restoration-watchly
        version: v1
    spec:
      containers:
      - name: restoration-watchly
        image: incept1on/whatchly:front
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "10Mi"
            cpu: "100m"
          limits:
            memory: "10Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
