apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: siyuan
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Incept10n/inceptech.git
    targetRevision: master
    path: apps/siyuan
 server: https://kubernetes.default.svc
    namespace: siyuan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
